### ISSUE TITLE
안녕하세요 해당 프로젝트에 관심이 있어 찾아왔습니다.

### ISSUE THREAD

**Issue by minhoryang** [flutterstudygn/flutter_naver_map_plugin#1]
안녕하세요 해당 프로젝트에 관심이 있어 찾아왔습니다.

저는 flutter와 NaverMap SDK를 iOS에 붙여서 사용하려고 하는데요.
이 프로젝트에는 아직 iOS가 붙어있지 않아서 저도 하나 만들어보려합니다.

제가 궁금한 점은, 플러터스터디라고 되어있는데, 이게 어디에서 진행하는 스터디인지와, 제가 참여할 수 있는지 여부가 궁금합니다.
그리고 iOS도 작업하실 계획이 있으신지도 확인하고 싶습니다.

**Comment by Soogyo-In** [comment]
반갑습니다! 일단 이수역 근방에서 진행하는 스터디구요. 확정은 아니지만 두주 정도 진행하고 잠시 텀을 가지자는 이야기가 있습니다. 
본 프로젝트가 스터디만을 위한 프로젝트는 아니고 저도 개인적 필요에 의해 시작한거라 참여해주시면 저도 많이 도움이 됩니다ㅎㅎ 일단 ios를 1도 모르거든요;;
프로젝트는 올해 안으로 완성을 목표로 하고있습니다.

**Comment by theoffin** [comment]
안녕하세요, @Sugyo-In 님!
실제 서비스를 위해 직접 map 관련 flutter plugin을 만들고자 고군분투 중입니다.
혹시 해당 프로젝트가 아직 진행되고 있는지 궁금하여 글 남깁니다.

답변 기다리겠습니다!

**Comment by Soogyo-In** [comment]
@theoffin 현재 기존 작업하던 것에 대해 재작업중입니다. 진행상태에 관해서는 조만간 project탭에 정리해서 관리해볼까합니다.
