### ISSUE TITLE
사용법과 진행사항에 대해

### ISSUE THREAD

**Issue by JAICHANGPARK** [flutterstudygn/flutter_naver_map_plugin#2]
현재 개발 진행이 어디까지 되어 있는지 알고싶습니다 .
예제 파일이 비어있어서 사용방법이 구체적으로 도출되어 있는건가요?

**Comment by Soogyo-In** [comment]
아직 진행상황은 많이 더딥니다. 사용법은 추후 추가할 예정이며 잠정 중단되었던 프로젝트인데 다시 시작해서 작업하고있습니다. 안드로이드 쪽은 3월 안으로 정리하려고 하는 중입니다.

**Comment by JAICHANGPARK** [comment]
@Sugyo-In  좋은 소식이네요 !  감사합니다
