### ISSUE TITLE
안드로이드 핫리로드시 앱 crash

### ISSUE THREAD

**Issue by yoonjaepark** [flutterstudygn/flutter_naver_map_plugin#9]
안드로이드 핫리로드시 앱 crash로 죽게되는데 이유가 있을까요??

**Comment by Soogyo-In** [comment]
그러게요... hot restart의 경우는 지도 객체가 destory된 후에 다시 생성이 안되는지 지도가 보이지 않고... 이래 저래 찾아보고있는데 어렵습니다;
hot reload의 경우 네이버 지도의 ndk 라이브러리에서 나는 에러 갔습니다. 
logcat 메세지를 보고 libnavermap.so를 addr2line으로 읽어본 결과 std::__ndk1::__assoc_sub_state::~__assoc_sub_state()라고 나오는 걸로 보니 __assoc_sub_state의 소멸자에서 뭔가 문제가 생기는 것 같은데 주말동안 계속 찾아봤지만 알 수 있는게 없네요;;

**Comment by yoonjaepark** [comment]
네... 그렇군요 멋지십니다.
화이팅하세요!

**Comment by Soogyo-In** [comment]
[google maps flutter](https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter)의 구조를 보고 작업중인데 Android쪽 지도 생성 코드에서 굳이 이럴 필요가 있나 싶은 부분이 있어 생략한게 몇 있습니다. 그 부분에서 생기는 문제인가 싶어 이슈 다시 열고 해결되면 닫도록 하겠습니다.
